### ISSUE TITLE
Analyze existing solutions for autocompletion

### ISSUE THREAD

**Issue by vityaman** [vityaman/ydb#2]
The goal of this task is to research existing solutions for an autocomplete on the market. Extract technologies used, methods, algorithms and so on, and then analyze and compare them.

Plan draft:
- [ ] YQL Autocompletion for [Gravity UI WebSQL Autocomplete](https://github.com/gravity-ui/websql-autocomplete) (TypeScript, ANTLRv4)
  - [x] [Article: ANTLRv4 Tutorial](https://tomassetti.me/antlr-mega-tutorial/)
  - [x] [Article: Autocompletion with ANTLR4-c3](https://tomassetti.me/code-completion-with-antlr4-c3/)
  - [x] [Article: with ANTLR4](https://tomassetti.me/autocompletion-editor-antlr/)
  - [x] [ANTLR4 C3](https://github.com/mike-lischke/antlr4-c3)
- Yandex Cloud SQL IDE (https://yq.yandex.cloud/folders/{folder_id}/ide)
- Database
  - [x] Postgres
    - Uses GNU Readline
    - Looks at last 6 tokens backward for decision making
    - Lookup system catalog for an identifier suggestion
    - [bin/psql/tab-complete.c](https://github.com/postgres/postgres/blob/REL_17_BETA2/src/bin/psql/tab-complete.c#L1637)
  - [x] ClickHouse
    - Uses [replxx](https://github.com/AmokHuginnsson/replxx/tree/master)
    - Loads identifiers at initialization with a huge system catalog query
    - Keeps the list of words to suggest
    - Updates it on some DDL queries executed, from where it extracts names
    - It receives keywords from that huge system catalog query
    - `suggestions = words.filter(_.startsWith(input.words.last))`
    - [ReplxxLineReader](https://github.com/ClickHouse/ClickHouse/blob/v24.7.1.1-new/src/Client/ReplxxLineReader.cpp#L339)
    - [LineReader::Suggest::getCompletions](https://github.com/ClickHouse/ClickHouse/blob/v24.7.1.1-new/src/Client/LineReader.cpp#L66)
  - [x] MySQL
    - Uses GNU Readline
    - Looks like the same approach as in ClichHouse, because of [only prefix comparison at completion_hash](https://github.com/mysql/mysql-server/blob/527c12ed611f3fe072c3043734319edb2c733099/client/completion_hash.cc#L123), it is used in `find_all_matches` and then in `new_command_generator`
    - [client/mysql.cc](https://github.com/mysql/mysql-server/blob/527c12ed611f3fe072c3043734319edb2c733099/client/mysql.cc#L2997)
  - [x] SQL Lite
    - Uses GNU Readline
    - `SELECT DISTINCT candidate COLLATE nocase FROM completion({text}) ORDER BY 1`
    - [ext/misc/completion.c](https://github.com/sqlite/sqlite/blob/version-3.46.0/ext/misc/completion.c#L193)
- [ ] [Language Server Protocol](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/)
  - [ ] [gopls](https://github.com/golang/tools/tree/master/gopls)
    - Hard to understand
    - [internal/golang/completion/completion.go](https://github.com/golang/tools/blob/master/gopls/internal/golang/completion/completion.go)
  - [ ] [v-analyzer](https://github.com/v-analyzer/v-analyzer/blob/main/server/features_completion.v#L31)
    - Uses [Tree Sitter](https://tree-sitter.github.io/tree-sitter)
    - Propose completion based on AST and position in text
      `CompletionProvider (is_available(Context), add_completion(Context, ResultSet))`
    - On completion examine the whole list of predefined providers
  - [ ] [clangd](https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clangd/CodeComplete.cpp#L1574)
    - Hard to read
  - [ ] rust-analyzer
- [ ] Check Tree Sitter autocomplete

**Comment by vityaman** [comment]
After having a quick look at existing implementations of this feature I have an impression that they are ugly. I have an idea that it is better to check how language servers provide this feature because they should be more clean. Also websql autocomplete looks pretty.

**Comment by vityaman** [comment]
Check how fish autosuggestions

**Comment by vityaman** [comment]
# Summary of existing solutions

I have chosen 4 SQL like databases for consideration of their CLI autocompletion: Postgres, ClickHouse, MySQL, SQL Lite. 

## Postgres

Postgres uses `GNU Readline` library for providing CLI autocompletion feature. It keeps tracking a list of words (where `words = input().split()`) as a completion context. They invented a DSL for pattern matching. Example code fragment using that DSL:

```c++
else if (TailMatches("CREATE", "OR", "REPLACE")) {
  COMPLETE_WITH(
    "FUNCTION", "PROCEDURE", "LANGUAGE", "RULE", 
    "VIEW",  "AGGREGATE", "TRANSFORM", "TRIGGER"
  );
}
```

Some DSL constructs:

```c++
/* Match the last N words before point, case-insensitively. */
#define TailMatches(...) /* ... */

/* Match N words representing all of the line, case-insensitively. */
#define Matches(...) /* ... */

/* Match the first N words on the line, case-insensitively. */
#define HeadMatches(...) /* ... */

#define COMPLETE_WITH(...) /* ... */

#define COMPLETE_WITH_ATTR(relation) /* ... */

#define COMPLETE_WITH_QUERY(query) /* ... */
```

Suggesting keywords is simple as uses only hard-coded list of values. Identifiers completion is more challenging and requires querying the system catalog relations, so on each tab push on position considered as a place for identifier, some SELECT query will be executed according to input prefix context.

**Comment by vityaman** [comment]
# Syntax Analysis Tools

## ANTLRv4 & ANTLRv4-C3

[ANTLRv4 C3](https://github.com/mike-lischke/antlr4-c3) is a grammar agnostic code completion engine for ANTLR4 based parsers. While primarily is written in TypeScript, has ports for `C++`, `Java` and `C#`. It is used in [Gravity UI WebSQL Autocomplete](https://github.com/gravity-ui/websql-autocomplete) and works well.

### Advantages

1. Popular, well documented and explored by community.

2. Used in `Gravity UI WebSQL Autocomplete` so we have expertise in using this tool.

3. `YQL` grammar is already written at [Gravity UI WebSQL Autocomplete](https://github.com/gravity-ui/websql-autocomplete/blob/v10.0.0/src/autocomplete/databases/yql/grammar/YQL.g4)

### Disadvantages

1. Using an `ANTLRv4` which is becoming obsolete because [ANTLRv5](https://github.com/antlr/antlr5) is being developed. 

2. Reparses the whole input on each input change. (?)

3. Focused on parsing of a correct input.

## Tree Sitter

The [Tree Sitter](https://tree-sitter.github.io/tree-sitter/) is a parser generator tool and an incremental parsing library. It can build a concrete syntax tree for a source file and efficiently update the syntax tree as the source file is edited. It has `C` programming languages bindings.

**Comment by vityaman** [comment]
# Features that we would like

## Functional

**FR1**. `YDB CLI` at interactive mode, must suggest `keywords` on tab pressed.

**FR2**. `YDB CLI` at interactive mode, must suggest `table`, `view` and `column` names on tab pressed.

**FR3**. `YDB CLI` at interactive mode, must have a syntax highlight of a query text.

TODO: add requirements for remaining entities (`YQLEntity`)

## Technical

**TR1**. `YDB CLI` at interactive mode, must suggest words based on context (example: don't suggest a keyword, where table name is expected and vice versa).

## Resources

```typescript
export type YQLEntity =
    | 'externalDataSource'
    | 'externalTable'
    | 'view'
    | 'object'
    | 'tableStore'
    | 'table'
    | 'replication'
    | 'topic'
    | 'group'
    | 'user'
    | 'tableIndex'
    | 'topicConsumer';
// From Gravity UI WebSQL Autocomplete
```

**Comment by vityaman** [comment]
# Prototype iterations

## Stage 1: ClickHouse-like suggestions

The main goals of this stage are 
1. To design main components
2. To integrate interactive shell library

**Comment by vityaman** [comment]
# About technologies

`YDB CLI` already adopted `replxx` library for building CLI. 

As a parser, I propose to start with `ANTLRv4 C3` as it seems easier to use and so risk of missing deadlines is lower. Anyway, we can switch to `Tree Sitter` or some other parser later if it will be required. Also, in that way we will have an implementation to compare with.

So, I think that `ANTLRv4 C3` at least as a solution for first iterations is the best.

**Comment by vityaman** [comment]
Implementing an LSP seems to be overkill as we need only feature of autosuggestion.

**Comment by vityaman** [comment]
Fresh ideas:
1. Check `pg_cli` implementation.
2. Check python REPL suggestions implementation.
3. Check `textDocument/autocomplete` LSP method signature.
4. Check ANTLRv4 and ANTLRv4 C3 licenses.
5. Check Node.js and C++ interoperability.
6. Check YDB backend parser.

**Comment by vityaman** [comment]
[textDocument/completion](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion)

**Comment by vityaman** [comment]
ANTLRv4: [BSD-3-Clause license](https://github.com/antlr/antlr4?tab=BSD-3-Clause-1-ov-file#)
ANTLRv4 C3: [MIT license](https://github.com/mike-lischke/antlr4-c3#)

**Comment by vityaman** [comment]
Node.js and C++ interoperability seems to be a very hard thing.

**Comment by vityaman** [comment]
Also ANTLR4 C3 is used in MySQL Shell: https://github.com/mysql/mysql-shell/blob/9.0.1/mysqlshdk/libs/parser/code-completion/CodeCompletionCore.h

**Comment by vityaman** [comment]
Final Decision: https://github.com/vityaman/ydb/issues/2#issuecomment-2227951307
